# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brandon Lopes
email: brandonnlopes@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technology, philosophy, and the little things
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brandonlopes.ca" # the base hostname & protocol for your site
excerpt_separator: <!--more-->
permalink: none
# Build settings
markdown: kramdown
